version: '3.8'

services:
  server:
    image: 017820664772.dkr.ecr.ap-south-1.amazonaws.com/docker-test-server:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - app-network

  client:
    image: 017820664772.dkr.ecr.ap-south-1.amazonaws.com/docker-test-client:latest
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
